---
# ====== Application: APUNTIA ================================
identification: 
  name: APUNTIA
  alias: APUNTIA
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: false
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 8125799675085519

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: WKSP_WEB

globalization: 
  primary-language: English (en)
  document-direction: Language Default
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: Sistema RAG - Apuntes

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Dashboard

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: Navigation Menu # 8126569965085524

navigation-bar: 
  implementation: List
  list: Navigation Bar # 8127692946085540
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

subscription: 
  version-number: 44846833138158

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Sistema RAG - Apuntes

component-settings: 
- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 8121236056085508
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 44846239916673

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 8121582783085509
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 44846239916709

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 8121835845085510
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 44846239916736

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 8122157941085510
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 44846239916769

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 8122420049085511
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  settings: 
    attribute-1: Y

  subscription: 
    version-number: 44846239916807

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 8122750693085512
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 44846239916842

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 8123031195085512
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 44846239916874

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 8123371594085513
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 44846239916913

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 8123623852085514
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 44846239916953

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 8123933408085514
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 44846239916989

- # ====== Component Setting: NATIVE_IR ========================
  id: 8124296059085515
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 44846239917013

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 8124505477085516
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 44846239917042

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 8124870679085516
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 44846239917068

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 8125123164085517
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 44846239917092

