prompt --application/pages/page_00003
begin
--   Manifest
--     PAGE: 00003
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.7'
,p_default_workspace_id=>8063091551209590
,p_default_application_id=>103
,p_default_id_offset=>0
,p_default_owner=>'WKSP_WEB'
);
wwv_flow_imp_page.create_page(
 p_id=>3
,p_name=>'Chat ApuntIA'
,p_alias=>'CHAT-APUNTIA'
,p_step_title=>'Chat ApuntIA'
,p_autocomplete_on_off=>'OFF'
,p_javascript_code=>wwv_flow_string.join(wwv_flow_t_varchar2(
'let conversationId = null;',
'let isProcessing = false;',
'',
'$(document).ready(function() {',
'    console.log(''ApuntIA Chat inicializado'');',
'    initializeChat();',
'    ',
'    $(''#send-btn'').click(sendMessage);',
'    $(''#user-input'').keypress(function(e) {',
'        if (e.which == 13 && !e.shiftKey) {',
'            e.preventDefault();',
'            sendMessage();',
'        }',
'    });',
'});',
'',
'function initializeChat() {',
'    apex.server.process(''CREATE_CONVERSATION'', {',
unistr('        x01: ''Nueva conversaci\00F3n - '' + new Date().toLocaleString()'),
'    }, {',
'        success: function(data) {',
'            if (data.success) {',
'                conversationId = data.conversation_id;',
unistr('                console.log(''Conversaci\00F3n creada:'', conversationId);'),
unistr('                $(''#conversation-info'').text(''Conversaci\00F3n #'' + conversationId);'),
'            }',
'        },',
'        error: function(xhr, status, error) {',
'            console.error(''Error AJAX:'', error);',
'        }',
'    });',
'}',
'',
'function sendMessage() {',
'    const userInput = $(''#user-input'').val().trim();',
'    ',
'    if (!userInput) {',
'        apex.message.showErrors({',
'            type: "error",',
'            location: "page",',
'            message: "Por favor escribe una pregunta"',
'        });',
'        return;',
'    }',
'    ',
'    if (isProcessing) {',
'        return;',
'    }',
'    ',
'    isProcessing = true;',
'    $(''#send-btn'').prop(''disabled'', true);',
'    ',
'    appendUserMessage(userInput);',
'    $(''#user-input'').val('''');',
'    $(''#typing-indicator'').show();',
'    scrollToBottom();',
'    ',
'    apex.server.process(''GENERATE_RAG_RESPONSE'', {',
'        x01: userInput,',
'        x02: conversationId',
'    }, {',
'        success: function(data) {',
'            $(''#typing-indicator'').hide();',
'            ',
'            if (data.success) {',
'                if (data.conversation_id && !conversationId) {',
'                    conversationId = data.conversation_id;',
unistr('                    $(''#conversation-info'').text(''Conversaci\00F3n #'' + conversationId);'),
'                }',
'                ',
'                appendBotMessage(data.response);',
'                apex.message.showPageSuccess("Respuesta generada correctamente");',
'            } else {',
unistr('                appendBotMessage(''Lo siento, ocurri\00F3 un error: '' + (data.error || ''Error desconocido''));'),
'            }',
'            ',
'            isProcessing = false;',
'            $(''#send-btn'').prop(''disabled'', false);',
'            scrollToBottom();',
'        },',
'        error: function(xhr, status, error) {',
'            $(''#typing-indicator'').hide();',
'            console.error(''Error AJAX:'', error, xhr.responseText);',
'            appendBotMessage(''Lo siento, no pude conectar con el servidor.'');',
'            isProcessing = false;',
'            $(''#send-btn'').prop(''disabled'', false);',
'        }',
'    });',
'}',
'',
'function appendUserMessage(text) {',
'    const messageHtml = `',
'        <div class="user-message">',
'            <div style="background: #007bff; color: white; padding: 12px 16px; border-radius: 10px; max-width: 70%; box-shadow: 0 1px 2px rgba(0,0,0,0.1);">',
'                ${escapeHtml(text)}',
'            </div>',
'        </div>',
'    `;',
'    $(''#messages'').append(messageHtml);',
'}',
'',
'function appendBotMessage(text) {',
'    const formattedText = formatBotResponse(text);',
'    ',
'    const messageHtml = `',
'        <div class="bot-message" style="display: flex; align-items: start;">',
'            <div class="avatar" style="width: 40px; height: 40px; background: #1e3a5f; border-radius: 50%; display: flex; align-items: center; justify-content: center; color: white; margin-right: 10px;">',
'                <span class="fa fa-robot"></span>',
'            </div>',
'            <div class="message-content" style="background: white; padding: 12px 16px; border-radius: 10px; max-width: 70%; box-shadow: 0 1px 2px rgba(0,0,0,0.1);">',
'                ${formattedText}',
'            </div>',
'        </div>',
'    `;',
'    $(''#messages'').append(messageHtml);',
'}',
'',
'function formatBotResponse(text) {',
'    let formatted = text.replace(/\n/g, ''<br>'');',
unistr('    formatted = formatted.replace(/INFORMACI\00D3N ENCONTRADA:/g, ''<strong>\D83D\DCCB INFORMACI\00D3N ENCONTRADA:</strong>'');'),
unistr('    formatted = formatted.replace(/=== CONTEXTO RELEVANTE ===/g, ''<strong>\D83D\DCDA CONTEXTO RELEVANTE:</strong>'');'),
unistr('    formatted = formatted.replace(/--- Fragmento/g, ''<em>\D83D\DCC4 Fragmento</em>'');'),
'    return formatted;',
'}',
'',
'function escapeHtml(text) {',
'    const map = {',
'        ''&'': ''&amp;'',',
'        ''<'': ''&lt;'',',
'        ''>'': ''&gt;'',',
'        ''"'': ''&quot;'',',
'        "''": ''&#039;''',
'    };',
'    return text.replace(/[&<>"'']/g, m => map[m]);',
'}',
'',
'function scrollToBottom() {',
'    const container = $(''#chat-container'');',
'    container.animate({',
'        scrollTop: container[0].scrollHeight',
'    }, 300);',
'}'))
,p_javascript_code_onload=>wwv_flow_string.join(wwv_flow_t_varchar2(
'$(document).ready(function() {',
'    let conversationId = null;',
'    ',
unistr('    // Iniciar nueva conversaci\00F3n'),
'    function initConversation() {',
'        apex.server.process(''CREATE_CONVERSATION'', {',
unistr('            x01: ''Nueva conversaci\00F3n'''),
'        }, {',
'            success: function(data) {',
'                conversationId = data.conversation_id;',
unistr('                console.log(''Conversaci\00F3n iniciada:'', conversationId);'),
'            },',
'            error: function(xhr, status, error) {',
unistr('                console.error(''Error iniciando conversaci\00F3n:'', error);'),
'            }',
'        });',
'    }',
'    ',
'    // Enviar mensaje',
'    window.sendMessage = function() {',
'        const userInput = $(''#user-input'').val().trim();',
'        if (!userInput) return false;',
'        ',
'        // Mostrar mensaje del usuario',
unistr('        $(''#messages'').append(''<div class="user-message"><strong>T\00FA:</strong> '' + userInput + ''</div>'');'),
'        $(''#user-input'').val('''');',
'        ',
'        // Mostrar indicador de carga',
unistr('        $(''#messages'').append(''<div id="loading" class="system-message">ApuntIA est\00E1 pensando...</div>'');'),
'        $(''#chat-container'').scrollTop($(''#chat-container'')[0].scrollHeight);',
'        ',
'        // Llamar al proceso AJAX',
'        apex.server.process(''GENERATE_RAG_RESPONSE'', {',
'            x01: userInput,',
'            x02: conversationId',
'        }, {',
'            success: function(data) {',
'                $(''#loading'').remove();',
'                $(''#messages'').append(''<div class="bot-message"><strong>ApuntIA:</strong> '' + data.response + ''</div>'');',
'                $(''#chat-container'').scrollTop($(''#chat-container'')[0].scrollHeight);',
'            },',
'            error: function(xhr, status, error) {',
'                $(''#loading'').remove();',
'                $(''#messages'').append(''<div class="error-message">Error: No se pudo generar respuesta</div>'');',
'                console.error(''Error AJAX:'', error);',
'            }',
'        });',
'        ',
unistr('        return false; // Prevenir env\00EDo del formulario'),
'    }',
'    ',
'    // Event listeners',
'    $(''#send-btn'').click(function(e) {',
'        e.preventDefault(); // Prevenir comportamiento por defecto',
'        sendMessage();',
'        return false;',
'    });',
'    ',
'    $(''#user-input'').keypress(function(e) {',
'        if (e.which == 13) {',
unistr('            e.preventDefault(); // Prevenir env\00EDo del formulario'),
'            sendMessage();',
'            return false;',
'        }',
'    });',
'    ',
unistr('    // Inicializar conversaci\00F3n al cargar'),
'    initConversation();',
'});'))
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/* Chat wrapper centrado */',
'.chat-wrapper {',
'    max-width: 900px;',
'    margin: 0 auto;',
'    padding: 20px;',
'}',
'',
'/* Encabezado del chat */',
'.chat-header {',
'    background: #1e3a5f;',
'    color: white;',
'    padding: 15px;',
'    border-radius: 10px 10px 0 0;',
'}',
'',
'/* Tarjetas tipo flashcard */',
'.flashcard {',
'    border: 1px solid #ccc;',
'    border-radius: 8px;',
'    padding: 16px;',
'    margin: 10px 0;',
'    cursor: pointer;',
'    text-align: center;',
'    transition: transform 0.4s;',
'    background-color: white;',
'    box-shadow: 0 2px 6px rgba(0,0,0,0.2);',
'}',
'',
'.flashcard.flipped {',
'    background-color: #f0f0f0;',
'    transform: rotateY(180deg);',
'}',
''))
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'11'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(8178395080235426)
,p_plug_name=>'Chat Interface'
,p_title=>'Chat :D'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>4072358936313175081
,p_plug_display_sequence=>10
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<div class="chat-wrapper" style="max-width: 900px; margin: 0 auto;">',
'    <div class="chat-header" style="background: #1e3a5f; color: white; padding: 15px; border-radius: 10px 10px 0 0;">',
'        <h3 style="margin: 0;">',
'            <span class="fa fa-robot"></span> ApuntIA - Asistente de Estudio',
'        </h3>',
unistr('        <small id="conversation-info">Nueva conversaci\00F3n</small>'),
'    </div>',
'    ',
'    <div id="chat-container" style="height: 500px; overflow-y: auto; background: #f5f5f5; padding: 20px; border-left: 1px solid #ddd; border-right: 1px solid #ddd;">',
'        <div id="messages">',
'            <div class="bot-message" style="display: flex; align-items: start; margin-bottom: 15px;">',
'                <div class="avatar" style="width: 40px; height: 40px; background: #1e3a5f; border-radius: 50%; display: flex; align-items: center; justify-content: center; color: white; margin-right: 10px;">',
'                    <span class="fa fa-robot"></span>',
'                </div>',
'                <div class="message-content" style="background: white; padding: 12px 16px; border-radius: 10px; max-width: 70%; box-shadow: 0 1px 2px rgba(0,0,0,0.1);">',
unistr('                    \00A1Hola! Soy ApuntIA, tu asistente de estudio. Puedo ayudarte a encontrar informaci\00F3n en tus documentos. \00BFQu\00E9 necesitas saber?'),
'                </div>',
'            </div>',
'        </div>',
'        ',
'        <div id="typing-indicator" style="display: none; margin: 10px 0;">',
'            <div class="bot-message" style="display: flex; align-items: center;">',
'                <div class="avatar" style="width: 40px; height: 40px; background: #1e3a5f; border-radius: 50%; display: flex; align-items: center; justify-content: center; color: white; margin-right: 10px;">',
'                    <span class="fa fa-robot"></span>',
'                </div>',
'                <div class="typing-dots" style="background: white; padding: 12px 20px; border-radius: 10px;">',
unistr('                    <span>\25CF</span>'),
unistr('                    <span>\25CF</span>'),
unistr('                    <span>\25CF</span>'),
'                </div>',
'            </div>',
'        </div>',
'    </div>',
'    ',
'    <div class="chat-input-area" style="background: white; padding: 15px; border: 1px solid #ddd; border-radius: 0 0 10px 10px;">',
'        <div style="display: flex; gap: 10px;">',
'            <input type="text" ',
'                   id="user-input" ',
'                   placeholder="Escribe tu pregunta sobre los documentos..." ',
'                   style="flex: 1; padding: 12px; border: 1px solid #ddd; border-radius: 25px; font-size: 14px;">',
'            <button id="send-btn" ',
'                    class="t-Button t-Button--hot" ',
'                    style="border-radius: 25px; padding: 0 25px;">',
'                <span class="fa fa-paper-plane"></span> Enviar',
'            </button>',
'        </div>',
'        <div style="margin-top: 10px; font-size: 12px; color: #666;">',
unistr('            \D83D\DCA1 Tip: Pregunta sobre conceptos espec\00EDficos de tus apuntes'),
'        </div>',
'    </div>',
'</div>'))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(9003791047471331)
,p_plug_name=>'Breadcrumb'
,p_region_template_options=>'#DEFAULT#:t-BreadcrumbRegion--useBreadcrumbTitle'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>2531463326621247859
,p_plug_display_sequence=>10
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_imp.id(8126008590085522)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>4072363345357175094
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(8178203642235425)
,p_process_sequence=>10
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'GENERATE_RAG_RESPONSE'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    v_response CLOB;',
'    v_conversation_id NUMBER;',
'BEGIN',
'    BEGIN',
'        v_conversation_id := TO_NUMBER(apex_application.g_x02);',
'    EXCEPTION',
'        WHEN OTHERS THEN',
'            v_conversation_id := NULL;',
'    END;',
'    ',
'    v_response := PKG_APUNTIA_RAG.generate_rag_response(',
'        p_user_query => apex_application.g_x01,',
'        p_conversation_id => v_conversation_id,',
'        p_user_id => :APP_USER',
'    );',
'    ',
'    apex_json.open_object;',
'    apex_json.write(''success'', true);',
'    apex_json.write(''response'', v_response);',
'    apex_json.write(''conversation_id'', NVL(v_conversation_id, 0));',
'    apex_json.close_object;',
'    ',
'EXCEPTION',
'    WHEN OTHERS THEN',
'        apex_json.open_object;',
'        apex_json.write(''success'', false);',
'        apex_json.write(''error'', ''Error: '' || SQLERRM);',
unistr('        apex_json.write(''response'', ''Lo siento, ocurri\00F3 un error procesando tu consulta.'');'),
'        apex_json.close_object;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>8178203642235425
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(8178419321235427)
,p_process_sequence=>10
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'CREATE_CONVERSATION'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    v_conversation_id NUMBER;',
'BEGIN',
'    v_conversation_id := PKG_APUNTIA_RAG.create_conversation(',
'        p_user_id => :APP_USER,',
'        p_title => apex_application.g_x01',
'    );',
'    ',
'    apex_json.open_object;',
'    apex_json.write(''success'', true);',
'    apex_json.write(''conversation_id'', v_conversation_id);',
'    apex_json.close_object;',
'EXCEPTION',
'    WHEN OTHERS THEN',
'        apex_json.open_object;',
'        apex_json.write(''success'', false);',
'        apex_json.write(''error'', SQLERRM);',
'        apex_json.close_object;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>8178419321235427
);
wwv_flow_imp.component_end;
end;
/
